version: 2.1
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: cimg/node:16.13.2
        steps:
            - checkout

            - run:
                  name: Update NPM
                  command: 'sudo npm install -g npm'
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  command: npm run test
                  name: Run tests
            - run:
                  name: Build React App
                  command: npm run build
            - save_cache:
                  key: app-build-cache-{{ .Branch }}
                  paths:
                      - ./build
            - run:
                  name: install netlify
                  command: sudo npm install netlify-cli -g --unsafe-perm
            - run:
                  name: Deploy to Netlify
                  # command: deploy — dir=./public -p -site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
                  command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
workflows:
    version: 2
    build-deploy:
        jobs:
            - build:
                  filters:
                      branches:
                          only:
                              - main
        # test_and_deploy: # this can be any name you choose
        #     executor: node/default
        #     steps:
        #         - checkout
        #         - node/install-packages:
        #               pkg-manager: npm
        #         - run:
        #               command: npm run test
        #               name: Run tests
        #         - persist_to_workspace:
        #               root: ~/project
        #               paths:
        #                   - .
# workflows:
#     test_my_app:
#         jobs:
#             - test_and_deploy
#             - deploy:
#                   requires:
#                       - test_and_deploy # only deploy if the build_and_test job has completed
#                   filters:
#                       branches:
#                           only: main # only deploy when on main
