version: 2.1

orbs:
    node: circleci/node@4.7

jobs:
    test_and_deploy: # this can be any name you choose
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: npm
            - run:
                  command: npm run test
                  name: Run tests
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - .

workflows:
    test_my_app:
        jobs:
            - build_and_deploy
            - deploy:
                  requires:
                      - build_and_test # only deploy if the build_and_test job has completed
                  filters:
                      branches:
                          only: main # only deploy when on main
